"""empty message

Revision ID: be570b7ecb63
Revises: 
Create Date: 2024-10-04 13:20:36.386147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be570b7ecb63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Repka', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('Name', sa.String(length=128), nullable=True),
    sa.Column('Status', sa.String(length=16), nullable=True),
    sa.Column('Area', sa.String(length=5), nullable=True),
    sa.Column('TimePyrge', sa.Integer(), nullable=True),
    sa.Column('TimeSpray', sa.Integer(), nullable=True),
    sa.Column('TimeStart', sa.DateTime(), nullable=True),
    sa.Column('TimeAsk', sa.Integer(), nullable=True),
    sa.Column('Result', sa.String(length=64), nullable=True),
    sa.Column('FirstPhoto', sa.String(length=64), nullable=True),
    sa.Column('BestPhoto', sa.String(length=64), nullable=True),
    sa.Column('LastPhoto', sa.String(length=64), nullable=True),
    sa.Column('ControlStatus', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('monitor')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
